In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
test = pd.read_csv("test.csv")
train = pd.read_csv("train.csv")

In [4]:
train.index

RangeIndex(start=0, stop=3000, step=1)

In [5]:
# df.index
len(train.columns)

49

In [6]:
len(test.columns)

48

In [7]:
train.head()

,index,Order,MS SubClass,MS Zoning,Lot Area,Lot Shape,Land Contour,Lot Config,Neighborhood,Bldg Type,...,Garage Cars,Garage Area,Paved Drive,Wood Deck SF,Open Porch SF,Mo Sold,Yr Sold,Sale Type,Sale Condition,SalePrice
0,200,2163,20,RL,9000,Reg,Lvl,Inside,NAmes,1Fam,...,1.998003,381.014258,Y,0,0,7,2007,WD,Normal,158000
1,3832,1862,20,RL,9600,Reg,Lvl,Inside,CollgCr,1Fam,...,1.998003,384.114652,Y,0,0,11,2007,WD,Normal,145000
2,4927,754,20,RL,9600,Reg,Lvl,Inside,NridgHt,1Fam,...,2.998015,625.140330,Y,0,0,5,2008,WD,Normal,125000
3,4088,641,80,RL,9600,Reg,Lvl,Inside,OldTown,1Fam,...,0.998002,193.156275,Y,0,0,7,2006,WD,Normal,135000
4,3644,754,20,RL,9600,Reg,Lvl,Inside,NoRidge,1Fam,...,2.998012,617.903766,Y,0,0,7,2007,WD,Normal,175000

In [8]:
train['Lot Shape'].unique()

array(['Reg', 'IR1'], dtype=object)

In [9]:
from sklearn.preprocessing import LabelEncoder

In [10]:
all_df = pd.concat([train, test], sort=False).reset_index(drop= True)

In [11]:
categories = all_df.columns[all_df.dtypes == "object"]
print(categories)

Index(['MS Zoning', 'Lot Shape', 'Land Contour', 'Lot Config', 'Neighborhood',
       'Bldg Type', 'House Style', 'Roof Style', 'Exterior 1st',
       'Exterior 2nd', 'Exter Qual', 'Foundation', 'Heating QC', 'Central Air',
       'Electrical', 'Kitchen Qual', 'Paved Drive', 'Sale Type',
       'Sale Condition'],
      dtype='object')

In [12]:
all_df.dtypes

index               int64
Order               int64
MS SubClass         int64
MS Zoning          object
Lot Area            int64
Lot Shape          object
Land Contour       object
Lot Config         object
Neighborhood       object
Bldg Type          object
House Style        object
Overall Qual        int64
Overall Cond        int64
Year Built          int64
Year Remod/Add      int64
Roof Style         object
Exterior 1st       object
Exterior 2nd       object
Exter Qual         object
Foundation         object
BsmtFin SF 1      float64
BsmtFin SF 2      float64
Bsmt Unf SF       float64
Total Bsmt SF     float64
Heating QC         object
Central Air        object
Electrical         object
1st Flr SF          int64
2nd Flr SF          int64
Gr Liv Area         int64
Bsmt Full Bath    float64
Bsmt Half Bath    float64
Full Bath           int64
Half Bath           int64
Bedroom AbvGr       int64
Kitchen AbvGr       int64
Kitchen Qual       object
TotRms AbvGrd       int64
Fireplaces          int64
Garage Cars       float64
Garage Area       float64
Paved Drive        object
Wood Deck SF        int64
Open Porch SF       int64
Mo Sold             int64
Yr Sold             int64
Sale Type          object
Sale Condition     object
SalePrice         float64
dtype: object

In [13]:
all_df["Lot Shape"].value_counts()

Reg    4066
IR1     934
Name: Lot Shape, dtype: int64

In [14]:
categories[0]

'MS Zoning'

In [15]:
for i in categories:
    print(all_df[i].value_counts())
    print("-----------------")

RL    4658
RM     259
FV      83
Name: MS Zoning, dtype: int64
-----------------
Reg    4066
IR1     934
Name: Lot Shape, dtype: int64
-----------------
Lvl    4973
Bnk      26
HLS       1
Name: Land Contour, dtype: int64
-----------------
Inside     4967
Corner       27
CulDSac       6
Name: Lot Config, dtype: int64
-----------------
NAmes      1919
OldTown     462
CollgCr     399
Gilbert     335
NridgHt     272
Sawyer      265
Somerst     215
Edwards     177
BrkSide     177
Crawfor     170
SawyerW     143
MeadowV      99
NWAmes       79
NoRidge      58
NPkVill      46
ClearCr      42
Blmngtn      36
StoneBr      31
IDOTRR       25
Timber       24
Mitchel      23
BrDale        2
Veenker       1
Name: Neighborhood, dtype: int64
-----------------
1Fam      4723
TwnhsE     155
Twnhs       51
Duplex      44
2fmCon      27
Name: Bldg Type, dtype: int64
-----------------
1Story    3433
2Story    1118
1.5Fin     232
SLvl       160
SFoyer      57
Name: House Style, dtype: int64
-----------------
Gable    4902
Hip        98
Name: Roof Style, dtype: int64
-----------------
VinylSd    3332
HdBoard     615
MetalSd     503
Wd Sdng     238
Plywood     128
CemntBd     115
Stucco       45
BrkFace      24
Name: Exterior 1st, dtype: int64
-----------------
VinylSd    3349
HdBoard     592
MetalSd     458
Plywood     258
Wd Sdng     195
CmentBd     133
Brk Cmn      12
Stucco        2
AsbShng       1
Name: Exterior 2nd, dtype: int64
-----------------
TA    3788
Gd    1196
Ex      16
Name: Exter Qual, dtype: int64
-----------------
CBlock    2468
PConc     2182
BrkTil     346
Slab         4
Name: Foundation, dtype: int64
-----------------
Ex    3384
TA    1454
Gd     162
Name: Heating QC, dtype: int64
-----------------
Y    4966
N      34
Name: Central Air, dtype: int64
-----------------
SBrkr    4960
FuseA      39
FuseF       1
Name: Electrical, dtype: int64
-----------------
TA    3410
Gd    1528
Ex      61
Fa       1
Name: Kitchen Qual, dtype: int64
-----------------
Y    4997
N       3
Name: Paved Drive, dtype: int64
-----------------
WD     4880
New     120
Name: Sale Type, dtype: int64
-----------------
Normal     4896
Partial     104
Name: Sale Condition, dtype: int64
-----------------

In [16]:
for cat in categories:
    le = LabelEncoder()
    print(cat)
    
    all_df[cat].fillna("missing", inplace = True)
    le = le.fit(all_df[cat])
    all_df[cat] = le.transform(all_df[cat])
    all_df[cat] = all_df[cat].astype("category")

MS Zoning
Lot Shape
Land Contour
Lot Config
Neighborhood
Bldg Type
House Style
Roof Style
Exterior 1st
Exterior 2nd
Exter Qual
Foundation
Heating QC
Central Air
Electrical
Kitchen Qual
Paved Drive
Sale Type
Sale Condition

In [17]:
all_df

,index,Order,MS SubClass,MS Zoning,Lot Area,Lot Shape,Land Contour,Lot Config,Neighborhood,Bldg Type,...,Garage Cars,Garage Area,Paved Drive,Wood Deck SF,Open Porch SF,Mo Sold,Yr Sold,Sale Type,Sale Condition,SalePrice
0,200,2163,20,1,9000,1,2,2,11,0,...,1.998003,381.014258,1,0,0,7,2007,1,0,158000.0
1,3832,1862,20,1,9600,1,2,2,4,0,...,1.998003,384.114652,1,0,0,11,2007,1,0,145000.0
2,4927,754,20,1,9600,1,2,2,15,0,...,2.998015,625.140330,1,0,0,5,2008,1,0,125000.0
3,4088,641,80,1,9600,1,2,2,16,0,...,0.998002,193.156275,1,0,0,7,2006,1,0,135000.0
4,3644,754,20,1,9600,1,2,2,14,0,...,2.998012,617.903766,1,0,0,7,2007,1,0,175000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,3138,2447,120,1,3907,0,2,2,20,0,...,1.998003,641.261977,1,0,0,6,2007,1,0,NaN
4996,191,27,120,1,3907,0,2,2,10,0,...,1.998007,387.032024,1,0,0,7,2008,1,0,NaN
4997,3294,208,50,1,6000,1,2,2,5,0,...,1.998007,406.608942,1,0,0,7,2009,1,0,NaN
4998,3073,1293,120,1,1680,1,2,2,6,0,...,-0.001999,-0.001395,1,0,0,6,2009,1,0,NaN
4999,361,1027,20,1,7200,1,2,2,11,0,...,1.998003,379.578413,1,0,0,7,2007,1,0,NaN

In [18]:
train_df_le = all_df[~all_df["SalePrice"].isnull()]
test_df_le=  all_df[all_df["SalePrice"].isnull()]

In [1]:
pip install lightgbm

Collecting lightgbm
  Using cached lightgbm-3.1.0.tar.gz (754 kB)
Requirement already satisfied: numpy in c:\python38-32\lib\site-packages (from lightgbm) (1.18.1)
Requirement already satisfied: scipy in c:\python38-32\lib\site-packages (from lightgbm) (1.4.1)
Requirement already satisfied: scikit-learn!=0.22.0 in c:\python38-32\lib\site-packages (from lightgbm) (0.22.2.post1)
Requirement already satisfied: joblib>=0.11 in c:\python38-32\lib\site-packages (from scikit-learn!=0.22.0->lightgbm) (0.14.1)
Requirement already satisfied: scipy in c:\python38-32\lib\site-packages (from lightgbm) (1.4.1)
Requirement already satisfied: numpy in c:\python38-32\lib\site-packages (from lightgbm) (1.18.1)
Requirement already satisfied: numpy in c:\python38-32\lib\site-packages (from lightgbm) (1.18.1)
Using legacy 'setup.py install' for lightgbm, since package 'wheel' is not installed.
Installing collected packages: lightgbm
    Running setup.py install for lightgbm: started
    Running setup.py install for lightgbm: finished with status 'error'
Note: you may need to restart the kernel to use updated packages.

    ERROR: Command errored out with exit status 1:
     command: 'c:\python38-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Public\\Documents\\Wondershare\\CreatorTemp\\pip-install-qi7f8dx7\\lightgbm_9f2bdc52e277433aa9469068cdb6bab3\\setup.py'"'"'; __file__='"'"'C:\\Users\\Public\\Documents\\Wondershare\\CreatorTemp\\pip-install-qi7f8dx7\\lightgbm_9f2bdc52e277433aa9469068cdb6bab3\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Public\Documents\Wondershare\CreatorTemp\pip-record-ryrelt6u\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\python38-32\Include\lightgbm'
         cwd: C:\Users\Public\Documents\Wondershare\CreatorTemp\pip-install-qi7f8dx7\lightgbm_9f2bdc52e277433aa9469068cdb6bab3\
    Complete output (16 lines):
    running install
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Public\Documents\Wondershare\CreatorTemp\pip-install-qi7f8dx7\lightgbm_9f2bdc52e277433aa9469068cdb6bab3\setup.py", line 286, in <module>
        setup(name='lightgbm',
      File "c:\python38-32\lib\site-packages\setuptools\__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "c:\python38-32\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\python38-32\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "c:\python38-32\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\Public\Documents\Wondershare\CreatorTemp\pip-install-qi7f8dx7\lightgbm_9f2bdc52e277433aa9469068cdb6bab3\setup.py", line 239, in run
        raise Exception("Cannot install LightGBM in 32-bit Python, "
    Exception: Cannot install LightGBM in 32-bit Python, please use 64-bit Python instead.
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\python38-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Public\\Documents\\Wondershare\\CreatorTemp\\pip-install-qi7f8dx7\\lightgbm_9f2bdc52e277433aa9469068cdb6bab3\\setup.py'"'"'; __file__='"'"'C:\\Users\\Public\\Documents\\Wondershare\\CreatorTemp\\pip-install-qi7f8dx7\\lightgbm_9f2bdc52e277433aa9469068cdb6bab3\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Public\Documents\Wondershare\CreatorTemp\pip-record-ryrelt6u\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\python38-32\Include\lightgbm' Check the logs for full command output.

In [2]:
brew install libomp

SyntaxError: invalid syntax (<ipython-input-2-6502e8fc9f2e>, line 1)